### ISSUE TITLE
Nov 3-2024 notes

### ISSUE THREAD

**Issue by AugustoLara** [hashed-io/hashed.io#12]
- [x] Soportar Outlook

![image](https://github.com/user-attachments/assets/acf1cd51-935c-4e85-a0ba-eb012b086e33)

- [x] Todos los status deberian de estar en español
- Pending   -> Pendiente
- Completed -> Verificado
- Alinear Validado

- [x] Si el pdf no es valido, notificar al usuario.
- [x]  Quitar boton de Cambiar estado y Click al valid, me sale una opcion de cambio manual de estado. Con un drop down de los estados y un boton de confirmacion Ok, Cancelar

- [x]  Razon de invalido deberia estar en español
<img width="858" alt="image" src="https://github.com/user-attachments/assets/5bf98b75-c557-4634-a526-d06941a5677f">

- [x]  inconsistencia de status

<img width="946" alt="image" src="https://github.com/user-attachments/assets/a5dcb739-ec5f-4913-b6d5-4ce00287b97f">

- [x]  Nombre Completo *se usara para verificar los documentos

<img width="602" alt="image" src="https://github.com/user-attachments/assets/daaed8e5-d6ee-4c27-b568-52ec4c7c931b">

- [x] Esconder fecha de entrega. Pedir telefono. Pedir estado civil.
<img width="481" alt="image" src="https://github.com/user-attachments/assets/0d90fecf-fa88-4b2b-94fd-2bbc379d50e0">

- [x]  tab y URL todayvia dicen document managment
<img width="613" alt="image" src="https://github.com/user-attachments/assets/e4f8fccb-b229-4b42-96a6-261d64c4611d">

- [x] Quitar Refrescar

<img width="414" alt="image" src="https://github.com/user-attachments/assets/6e3aab16-b3b6-41da-a96e-7320ae343174">

- [x]  Espacios en el texto y hacerlo mas conciso
<img width="534" alt="image" src="https://github.com/user-attachments/assets/ecc50046-4443-4218-a552-408c9e995ca5">

- [x]  INE debemos cubrir el caso en el que viene en un solo documento
- [x]  Agregar documentos faltantes a la lista de docuemntos que pedimos y al flujo entero
- [x]  Poder ver los documentos que ya se subieron
- [x] Si se cambia el estado invalido, se deberia de poder especificar la razon de porque es invalido

**Comment by Dreyhh** [comment]
@AugustoLara @sebastianmontero ya esta arriba una version con la mayoria de los cambios [vinte-documentos.vercel.app](https://vinte-documentos.vercel.app/)
quedo al pendiente de cualquier comentario

**Comment by sebastianmontero** [comment]
Muchas gracias @Dreyhh! Algunos comentarios:
- Por alguna razón ya no me pude conectar con gmail
- Creo que faltaria mejorar algunas validaciones de por ejemplo subi un comprobante de domicilio y me arrojo el siguiente  error: "El documento no es válido porque la fecha de pago es el 04-SEP-2024, que ya ha pasado. Por lo tanto, el documento está expirado", se que esto no ha sido el enfoque principal.
- Quitar el guion bajo de los nombres de los documentos.
- Cambiar "stage" por "etapa"
- Creo que sería bueno involucrar a Chema para trabajar en la UI para que sea funcional cuando se tengan cientos de clientes como ves @AugustoLara? Soportar busqueda de clientes, paginación, etc
- El problema de timeout al subir multiples documentos se resolveria con la version de paga de vercel?

**Comment by Dreyhh** [comment]
- @sebastianmontero usaste tu cuenta gmail de hashed? por ahora solo funciona con cuentas dentro de la org de hashed
- De acuerdo, lo checo.  Igual estoy pensando en hacer los status description/analysis mas estructurados, en lugar que sea un solo 'status_description', agregar un 'analysis_result_id' a cada status y que cada analys_result tenga al menos las columnas type, result, reasoning , status_id. en principio al usuario solo le interesara ver el type y el result .
- Para el problema de timeout lo mas rapido seria usar la version de paga, pero igual se puede resolver haciendo self host y/o modificando el modo en el que se esperan los resultados, actualmente es algo naive simplemente se espera la respuesta del servidor, idelamente no esperariamos por la respuesta y habilitariamos un endpoint para recibirlo una vez el servidor complete el proceso, igual tengo que trabajar en mejorar el performance del codigo del server.  Por el momento hare el cambio de no esperar a que complete, eso debe solucionarlo.

**Comment by sebastianmontero** [comment]
- @Dreyhh  Pues me el siguiente error en cuanto le doy conectar con gmail:
![image](https://github.com/user-attachments/assets/5cb2a88c-411a-4685-b354-de18172e65f5)
- De acuerdo con el punto 2.
- En relacion al punto tres, si creo que el request inicial solo deberia de iniciar el analisis de los documentos, probablemente ejecutar un proceso(funcion) para cada uno de los documentos, estos procesos actualizan la base de datos, y la applicacion web consultar el status de la base de datos.

**Comment by AugustoLara** [comment]
@Dreyhh Veo que faltan dos puntos del ticket. Son los que estas trabajando?

**Comment by Dreyhh** [comment]
Done
