### ISSUE TITLE
Nov8 Feedback

### ISSUE THREAD

**Issue by AugustoLara** [hashed-io/hashed.io#13]
- [x] Ya que se conecta una cuenta deberia cambiar el boton 

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/4250405e-df93-441f-8dec-cd40dba9caf4">

- [x] Agregar: 1. cuandos del total tenemos 2. Fecha de registro (podemos hacer que haya sorting basado en cualquiera de los 4 campos?

- [x] Cambiar por Fecha de registro

<img width="283" alt="image" src="https://github.com/user-attachments/assets/84b44eb8-915d-4289-b013-2f1f4df26f50">

<img width="893" alt="image" src="https://github.com/user-attachments/assets/e1e86e74-92ce-4f1e-a92f-a878950ea146">

- [x] Falta o es invalido (evitemos que se vea como template

<img width="643" alt="image" src="https://github.com/user-attachments/assets/17d893f6-5c98-4985-9cb8-112834ee6f6b">

-[ ] 1. Logo de Vinte arriba/izquiera. 2. mover pagina arriba. 3. expacio superior derecho para connectar cuenta, verla conectada y desconectar (click en cuenta da opcion de desconectar (nadie conectara mas de una cuenta en Vinte)

![image](https://github.com/user-attachments/assets/11768950-d120-4eaf-b550-d2933a20dd6c)

- [x] Estandarizar el case a no case. Todo en español (Front Back). Probar con 5 drafts para distintas cuentas.

<img width="484" alt="image" src="https://github.com/user-attachments/assets/cfd16134-c391-416b-9367-bc63cac4ee3e">

- [x] Estimado / estimada. El LLM deberia saber el genero correcto
- [x] "Le escribo en calidad de Gustavo López,"? Soy Gustavo Lopez bla bla
- [x] El draft esta muy Kamala Harris word salad. No queremos que sea creativo. Friendly and concise.

"Espero que se encuentre bien. Le escribo en calidad de Gustavo López, Analista de Documentos en Vinte, para informarle acerca de la situación de los documentos que ha enviado recientemente para su trámite. Después de revisar detenidamente la documentación proporcionada, hemos identificado que algunos documentos necesarios no han sido adjuntados, o bien, presentan ciertas inconsistencias que requieren su atención.

En caso de que haya alguna duda sobre el motivo por el cual los documentos mencionados no han sido incluidos o no cumplen con los requisitos establecidos, no dude en contactarnos para brindarle la asistencia necesaria y garantizar que su trámite se lleve a cabo de manera correcta y oportuna.

Agradecemos su pronta atención a este requerimiento, ya que la documentación completa y correcta es fundamental para continuar con el proceso. Quedamos atentos a cualquier consulta adicional que pueda tener.

Quedo a sus órdenes para cualquier información adicional que requiera."

Vinte nos va a mandar algo pero por lo pronto usemos algo como este. Le diste un ejemplo al modelo?

_"Estimado César Augusto,

Soy Gustavo Lopez de Vinte y te escribo en nombre para solicitar nos mande los siguientes documentos para continuar con el proceso del Infonavit.

... requisitos

Estamos a sus ordenes si tiene cualquier duda o requiere  apoyo en este proceso

Saludos cordiales,

Gustavo López
Analista de Documentos
Vinte"_

<img width="599" alt="image" src="https://github.com/user-attachments/assets/046fee2c-a32e-42ce-a390-152fd33d8dae">

- [x] Confirmar que los follow ups tambien sean Friendly and concise

- [x] Signatures-research Si estan configuradas en Outlook las agrega al draft? Si si, ya estuvo. La quitamos del draft generator

       -[ ] Si no, necesitamos una manera de agregar signatures en la aplicacion. Idealmente cuando se conecta la cuenta, la siguiente pagina es agrega tu email signature to finish your account set up.
       
       
- [x] No agrega si docuemntos de matrimonio apesar de que este casada. Probar con 5 drafts.

<img width="635" alt="image" src="https://github.com/user-attachments/assets/df76dab3-bba9-4c4a-b4bd-6ba9b69c9cd1">

**Comment by AugustoLara** [comment]
FYI @Dreyhh tambien aqui veo un par que faltan.

**Comment by Dreyhh** [comment]
Done, sobre Signatures-research,Outlook solo guarda los signatures a nivel cliente y no en su API, entonces si va a ser necesario que el feature para que cada usuario pueda definit sus signatures, pero creo que seria buena idea crear un ticket aparte para eso (#16 )

**Comment by Dreyhh** [comment]
Done
